### ISSUE TITLE
Procedure To run this locally on windows operating system

### ISSUE THREAD

**Issue by iamidot** [rohit-95/inno#12]
got following error after trying to run it 

```
(node:12728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:12728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.
```

**Comment by rohit-gohri** [comment]
The website should still be running with this warning. 

If you could attach the full stack trace I might be able to point out where this rejection is coming from.

**Comment by iamidot** [comment]
```
(node:12356) UnhandledPromiseRejectionWarning: MongoParseError: Invalid connection string
    at parseConnectionString (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongodb\lib\core\uri_parser.js:565:21)
    at connect (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongodb\lib\operations\connect.js:282:3)
    at C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongodb\lib\mongo_client.js:224:5
    at maybePromise (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongodb\lib\utils.js:665:3)
    at MongoClient.connect (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongodb\lib\mongo_client.js:220:10)
    at C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\connection.js:820:12
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\connection.js:817:19)
    at C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\index.js:345:10
    at C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (C:\Users\Ruturaj\Downloads\inno-main\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (C:\Users\Ruturaj\Downloads\inno-main\app.js:19:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Ruturaj\Downloads\inno-main\bin\www:7:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:12356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.
```

(sorry for the inconvenience, I know having such skill set in tech you may really be busy ,but if possible plz add the steps to install this on windows for example in windows Kerberos Plugin should be install instead of libkrb5-dev right?? )

**Comment by rohit-gohri** [comment]
> (node:12356) UnhandledPromiseRejectionWarning: MongoParseError: Invalid connection string

From your logs, the mongo uri in "dbhost" config field is not correct. You can change the value in `config/default.json`.

**Comment by iamidot** [comment]
did tried 
```
PS C:\Users\Ruturaj\Downloads\inno-main (1)> npm start                                        
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Ruturaj\Downloads\inno-main (1)\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ruturaj\Downloads\inno-main (1)\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ruturaj\AppData\Roaming\npm-cache\_logs\2021-04-01T07_45_34_324Z-debug.log
PS C:\Users\Ruturaj\Downloads\inno-main (1)> 
```

**Comment by rohit-gohri** [comment]
> npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Ruturaj\Downloads\inno-main (1)\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.

Please try to debug such errors yourself, this is not a project specific error^ 

You are either in the wrong directory or some files have been accidentally deleted

**Comment by iamidot** [comment]
i did tried reinstalling the whole setup , using npm init nothing seems to work

**Comment by cybrot** [comment]
hey can you just configure it on a windows machine(local-host) and  add the same to readme.

**Comment by rohit-gohri** [comment]
Have updated the default config, scripts, Readme to make it easier to run locally with minimal changes. Could you pull the changes and try following the readme again?

Also, please change the domain names and contact emails before using this anywhere in production.

**Comment by iamidot** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle inno@0.0.1~prestart: inno@0.0.1
6 info lifecycle inno@0.0.1~start: inno@0.0.1
7 verbose lifecycle inno@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle inno@0.0.1~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ruturaj\Downloads\inno-main\inno-main\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Ruturaj\AppData\Local\Programs\Python\Python39;C:\Users\Ruturaj\AppData\Local\Programs\Python\Python39\Scripts;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\MongoDB\Server\4.4\bin;C:\Users\Ruturaj\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Ruturaj\AppData\Local\Programs\Python\Python39\;C:\Users\Ruturaj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ruturaj\AppData\Local\Microsoft\WindowsApps;C:\Users\Ruturaj\AppData\Local\GitHubDesktop\bin;C:\Users\Ruturaj\AppData\Roaming\npm;
9 verbose lifecycle inno@0.0.1~start: CWD: C:\Users\Ruturaj\Downloads\inno-main\inno-main
10 silly lifecycle inno@0.0.1~start: Args: [ '/d /s /c', 'NODE_ENV=production node ./bin/www' ]
11 silly lifecycle inno@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle inno@0.0.1~start: Failed to exec start script
13 verbose stack Error: inno@0.0.1 start: `NODE_ENV=production node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid inno@0.0.1
15 verbose cwd C:\Users\Ruturaj\Downloads\inno-main\inno-main
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error inno@0.0.1 start: `NODE_ENV=production node ./bin/www`
22 error Exit status 1
23 error Failed at the inno@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

 is this again some stupid mistake done by me?
this is my last attempt after this i may close the issue .
sorry for wasting your time.
used the updated inno files.....

**Comment by rohit-gohri** [comment]
I think I understood your problem this time, have pushed another fix. Do another `npm install` after pulling the changes and then run `npm run dev`.

Also in the future when pasting logs/code use code blocks around the logs to ignore formatting.
<pre>
```
logs here
```
</pre>
See example here : https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by iamidot** [comment]
```
C:\Users\Ruturaj\Downloads\inno-main (3)\inno-main\views\eventList.jade:52 50| h3.center.zero.intro Events 51| .row > 52| each event, index in events 53| .events.col.s12.m6.l4 54| .card.small.event 55| .card-image.waves-effect.waves-block.waves.light Cannot read property 'length' of undefined
```
when open event page with npm run dev:watch
other commands just give
```
Cannot read property 'length' of undefined
```
how to access admin/event manger panel?

**Comment by rohit-gohri** [comment]
To get access to admin panel, you'll have to manually mark a user as `is_admin: true` in the DB. 
You'll need [MongoDB Compass](https://www.mongodb.com/products/compass) or other similar tool for it.

1. Connect to DB
	
<img width="638" alt="image" src="https://user-images.githubusercontent.com/31949290/113467209-32cc8400-945f-11eb-8a7e-aed866c666fb.png">

2. Select `inno-site` DB
	<img width="684" alt="image" src="https://user-images.githubusercontent.com/31949290/113467220-40820980-945f-11eb-9bac-a4c0f46123e1.png">

3. Select `accounts` collection

	<img width="752" alt="image" src="https://user-images.githubusercontent.com/31949290/113467225-54c60680-945f-11eb-94f9-afd6e58a70e6.png">

4. Set `is_admin: true` for the required user

	<img width="1013" alt="image" src="https://user-images.githubusercontent.com/31949290/113467264-99ea3880-945f-11eb-93f9-217c80c098a3.png">

5. After that if you go to profile you'll have these extra buttons (also to add other event managers)
	<img width="528" alt="image" src="https://user-images.githubusercontent.com/31949290/113467307-cb630400-945f-11eb-9b6a-85c24c6dfd5f.png">

6. And if you are an admin or an EM you'll get access to edit event details and see participant info on event page

	<img width="499" alt="image" src="https://user-images.githubusercontent.com/31949290/113467375-3f9da780-9460-11eb-841f-3870928e4220.png">

**Comment by rohit-gohri** [comment]
> ```
> C:\Users\Ruturaj\Downloads\inno-main (3)\inno-main\views\eventList.jade:52 50| h3.center.zero.intro Events 51| .row > 52| each event, index in events 53| .events.col.s12.m6.l4 54| .card.small.event 55| .card-image.waves-effect.waves-block.waves.light Cannot read property 'length' of undefined
> ```
>
> ```
> Cannot read property 'length' of undefined
> ```

I'm not able to reproduce these errors even on a fresh install with empty DB. Try adding some events and maybe that will fix it.

And to create a user you can just register with email/password.

**Comment by cybrot** [comment]
Cool the instructions worked very well ,
this having tons of feature you should consider making your readme more detailed in near future......

**Comment by iamidot** [comment]
After the connection of Mongo DB this issue was solved....
the website ran successfully...
this is indeed a amazing website let it be ui ux or the clean code......

**Comment by rohit-gohri** [comment]
> this having tons of feature you should consider making your readme more detailed in near future......

@cybrot Feel free to open a Pull Request adding some documentation. I made this 5 years ago so it's no longer useful for me.

**Comment by iamidot** [comment]
Hey what are photo ids and how to use them ? 
like i get faliure every time
I have migrated from jade to pug once I complete I would send a pull request .

**Comment by rohit-gohri** [comment]
Photo upload might be failing because currently paths are unix style:
https://github.com/rohit-gohri/inno/blob/be50c6150bfb69047d7df60ae56c21790e3eed3b/routes/users.js#L166

Will have to use [`path.join`](https://nodejs.org/dist/latest-v12.x/docs/api/path.html#path_path_join_paths) instead of string concat to support windows. Please open a separate issue for this if it's not solved by it.

**Comment by iamidot** [comment]
Can you specify the command that should be use I tried some didn't work .
I did add var path= require('path'); 
And change the concatenation but probably was unable to get the correct one.

**Comment by rohit-gohri** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/path.html#path_path_join_paths

**Comment by iamidot** [comment]
Yeah I tried some command but they didn't work,
Don't know if I use wrong command or it's due to the codes ......

**Comment by rohit-gohri** [comment]
Please open a new issue for this and add the full error that you are getting.

**Comment by iamidot** [comment]
Okay
