### ISSUE TITLE
Photo ids not working

### ISSUE THREAD

**Issue by iamidot** [rohit-95/inno#13]
when a photo id is uploaded it shows failure and log outs the user
after which if uploaded it shows success but dose not take any effect 

inno/routes/users.js

Line 166 in be50c61

 user.photoId = '/uploads/photoids/' + req.file.filename; 

 replaced to :
user.photoId = path.join('/uploads/photoids/', ' req.file.filename');

i did'nt get any error in commandline

**Comment by iamidot** [comment]
Is there no way to rectify this ?

**Comment by cybrot** [comment]
photo ids don't work even after hosting online

**Comment by rohit-gohri** [comment]
Could it be a permissions related issue? Folder permissions might be creating problems for it to write the file?

**Comment by iamidot** [comment]
no it's not working when hosted too

**Comment by rohit-gohri** [comment]
Okay. Just remembered that feature was not completed. We just ended up sourcing the photos from fb api. Though FB API might have changed significantly by now.

**Comment by iamidot** [comment]
okay

**Comment by iamidot** [comment]
any possible way you think will work?

**Comment by rohit-gohri** [comment]
You can use something like S3 to upload them to cloud rather than saving them locally on server.

**Comment by iamidot** [comment]
Hey how to use countdown timer?

**Comment by rohit-gohri** [comment]
Might have to add https://github.com/rohit-gohri/inno/blob/main/public/assets/javascripts/index_countdown.js to the homepage and uncomment the days/minutes/secs etc divs

**Comment by iamidot** [comment]
I hosted it using heroku but the uploads are temporary any solution without using aws S3

**Comment by rohit-gohri** [comment]
You will have to use some independent storage since Heroku shuts down the dynos when not in use, can be S3/Google Storage/anything outside of the filesystem. 

Also, share a link to your version? I would appreciate it if you also keep your version open source.

**Comment by iamidot** [comment]
My all project are and always will be open source :).
We are in diploma final year(after 10th).
This project is use for my Freinds final year as the engineering colleges are creating robots so my Freinds were going to buy  it, instead I got this repo and started extending to be used by them.i explained everything that I learned .
I am new to mean stack if you remember I wasn't able to locate folder at first used npm in wrong directory .
My technical stack is high level programing programs like creating operating system and programming language:
My final year project
https://github.com/rohitmaurya-png/SHARP-PROGRAMING-LANGUAGE

After reading some documentation I added some features as follow:
Jade to pug (got many errors but was successful)
A registered user will see a paynow  button 
Paytm payment integration is done but data does not store in mongo DB (don't know why)
A developer page is created.

Repo is private will be public once completed 

Any idea where can I learn how to use independent storage , also after final presentation I will send a pull request updating jade to pug .

How come your event images are still there can you tell me the procedure followed.
Deleting this comment after response:)......

**Comment by rohit-gohri** [comment]
> How come your event images are still there?

Since the events are no longer being changed, I just committed them to the repo. Previously I was hosting them on a Digital Ocean server.

> Any idea where can I learn how to use independent storage

Not sure. Heroku has some resouces: https://devcenter.heroku.com/articles/s3-upload-node but they require some AWS know how already. Don't know of any simple to use image service.

**Comment by iamidot** [comment]
I have sent you a pull request I tested on local host and it worked perfectly....

**Comment by iamidot** [comment]
Any issue with pull why it's not being merge ???

**Comment by rohit-gohri** [comment]
> Any issue with pull why it's not being merge ???

Will have to test it and verify that nothing breaks. Will review when I get time next.

**Comment by iamidot** [comment]
Yeah, waiting for a positive response.........

**Comment by iamidot** [comment]
Any issue?

**Comment by iamidot** [comment]
Any issue?

**Comment by iamidot** [comment]
Should I close the pull???

**Comment by rohit-gohri** [comment]
> Should I close the pull???

No, I'll review it soon. Don't have a local environment setup so it's going to be some amount of work to test it out

**Comment by iamidot** [comment]
Okay, thanks....
